### ISSUE TITLE
TypeError: column_alias is None

### ISSUE THREAD

**Issue by TomiBelan** [fmfi-svt/votr#120]
Zopar uzivatelov (konkretne traja) dostavaju tuto chybu:

```
Traceback (most recent call last):
  File "/var/www/votr-prod/votrfront/rpc.py", line 27, in rpc_handle_call
    result = encode_result(method(*args))
  File "/var/www/votr-prod/fladgejt/webui/hodnotenia.py", line 38, in get_priemery
    app = self._open_hodnotenia_priemery_app(zapisny_list_key)
  File "/var/www/votr-prod/fladgejt/webui/pool.py", line 47, in wrapper
    open_apps[app_key] = original_method(self, *args)
  File "/var/www/votr-prod/fladgejt/webui/studium.py", line 154, in _open_hodnotenia_priemery_app
    self.__vyber_zapisny_list(app, zapisny_list_key)
  File "/var/www/votr-prod/fladgejt/webui/studium.py", line 93, in __vyber_zapisny_list
    app.d.zapisneListyTable.select(zapisny_list_index)
  File "/var/www/votr-prod/aisikl/components/table.py", line 562, in select
    raise TypeError('column_alias is None')
TypeError: column_alias is None
```

https://github.com/fmfi-svt/votr/blob/1fbae0074cc8891748ea23f13f8a63751ae97fb9/aisikl/components/table.py#L560-L567

select() kontroluje ze ak sa v tabulke vyberaju jednotlive bunky, treba mu povedat aj ktory riadok aj ktory stlpec, a ak sa vyberaju cele riadky, treba povedat iba ktory riadok.

Ale ako je mozne, ze zapisneListyTable ma pre zlomok uzivatelov cell_selection_mode == True? Lebo AIS. *sigh* Ked si niekto zapne "Sprava pouzivatelov > Sprava pouzivatela > Nastavenia aplikacii > používať mód pre podporu čítacieho software JAWS", okrem ineho sa kazda tabulka v celom AISe prepne do cell_selection_mode.

Pre porovnanie, podobny problem bol v #104.

**Comment by mrshu** [comment]
@TomiBelan sorry, ze to takto dlho trvalo. Neviem, ci je toto preto, co spominas v tejto issue, ale ked som zapol JAWS a otvoril som "Moje Skusky", toto som dostal:

```
Traceback (most recent call last):
  File "/var/www/votr-beta/votrfront/rpc.py", line 56, in rpc_handle_exceptions
    result = rpc_handle_sessions(request, send_json)
  File "/var/www/votr-beta/votrfront/rpc.py", line 48, in rpc_handle_sessions
    result = rpc_handle_call(request, session)
  File "/var/www/votr-beta/votrfront/rpc.py", line 27, in rpc_handle_call
    result = encode_result(method(*args))
  File "/var/www/votr-beta/fladgejt/webui/terminy.py", line 72, in get_vypisane_terminy
    self.__vyber_oba_semestre(app)
  File "/var/www/votr-beta/fladgejt/webui/terminy.py", line 13, in __vyber_oba_semestre
    app.d.filterAction.execute()
  File "/var/www/votr-beta/aisikl/components/action.py", line 37, in execute
    self.dialog.app.send_events(ev)
  File "/var/www/votr-beta/aisikl/app.py", line 439, in send_events
    self.collect_component_changes())
  File "/var/www/votr-beta/aisikl/app.py", line 358, in _do_request
    self._process_response(response)
  File "/var/www/votr-beta/aisikl/app.py", line 429, in _process_response
    method(*args)
  File "/var/www/votr-beta/aisikl/components/table.py", line 416, in _ais_setDataView
    self._update_data(data_view)
  File "/var/www/votr-beta/aisikl/components/table.py", line 436, in _update_data
    raise AISParseError("Unsupported thead in dataTabTmp")
aisikl.exceptions.AISParseError: Unsupported thead in dataTabTmp
```
